# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-SCRIPT
echo sudo -i >> /home/vagrant/.bash_profile
sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/sysconfig/selinux
setenforce 0
yum -y update
yum -y install java
cat > /etc/yum.repos.d/cassandra.repo << xxx
[cassandra]
name=Apache Cassandra
baseurl=https://downloads.apache.org/cassandra/redhat/40x/
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://downloads.apache.org/cassandra/KEYS
xxx
yum -y update
yum -y install cassandra
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.define "srv1" do |srv|
    srv.vm.hostname = "srv1"
    srv.vm.network "private_network", ip: "192.168.33.10"
    srv.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.name = "cassandra"
    end
  end
  config.vm.provision "shell", inline: $script
end
