# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-SCRIPT
echo sudo -i >> /home/vagrant/.bash_profile
sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/sysconfig/selinux
setenforce 0
yum install -y git nano docker
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
sudo chmod +x /usr/bin/docker-compose
SCRIPT

Vagrant.configure("2") do |config|
 config.vm.define "mysql" do |mysql|
    mysql.vm.box = "centos/7"
    mysql.vm.hostname = "mysql"
    mysql.vm.network "private_network", ip: "192.168.33.10"
    mysql.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
      vb.name = "mysql"
    end
  config.vm.provision "shell", inline: $script
  end
end
